apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: s3-controller
  namespace: flux-system
spec:
  releaseName: s3-chart
  chart:
    spec:
      chart: ./helm
      sourceRef:
        kind: GitRepository
        name: s3-controller
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    serviceAccount:
      create: false
    aws:
      region: us-east-2
